[file]
# Имена файлов
case = save-30.cas.h5
data_start = save-30-1.509500.dat.h5
data_end = save-30-1.511500.dat.h5
data_qubiq = visit_ex_db_3D2.plt


[mode]
solver = QUBIQ							# тип решателя: FLUENT или QUBIQ
reload_data = yes						# нужно ли заново загрузить данные
mass_flow_rate = yes					# расчет RhoVx, вычисление расходов
combustion_efficiency_species = yes		# расчет RhoVx компонент, оценка полноты сгорания по расходам топлива и окислителя
combustion_efficiency_energetic = no	# расчет параметров для оценки энергетической полноты сгорания
pictures = yes							# отрисовка и сохранение рисунков
movies = no							    # запись анимаций
slices = no                             # делать ли экспорт на сечениях по нестационарным данным !!! ОЧЕНЬ ВРЕМЯЗАТРАТНО !!!
slices_3D_averaged = yes                # делать ли экспорт на сечениях по осредненным 3D полям
particles = no
show_time = yes                         # показать ли текущее время
average_3d_fields = yes                 # вычислять ли осредненные 3D поля - !!!ПЕРЕЗАПУСК после использования этой функции только без нестационарных обработок!!!


[path]
chemkin = D:\Simulation\!Python_CIAM\2_Comb_DES\kinetics\kerosene_air_14comp\chemkin_kerosene_air_14comp.txt
thermo = D:\Simulation\!Python_CIAM\2_Comb_DES\kinetics\kerosene_air_14comp\thermo_kerosene_air_14comp.db
work_dir = D:\Simulation\!TECPLOT_MACRO\PYTECPLOT\Result_2019\Stupa\


path_case_data = D:\YASIM\VORON\2026_12_Iskra_OPZ\FLUENT\06_LES_high_regenerated\2nd_mom_time
path_data_qubiq = D:\YASIM\VORON\2026_12_Iskra_OPZ\QUBIQ\LES_HOT_HIGH
dir_slices = slices
dir_pictures = pictures
dir_movies = movies

path_all_slices = D:\YASIM\VORON\2026_12_Iskra_OPZ\FLUENT\06_LES_high_regenerated\2nd_mom_time\slices_combo
path_plots_and_animations = D:\YASIM\VORON\2026_12_Iskra_OPZ\FLUENT\06_LES_high_regenerated\2nd_mom_time\plots_and_animations
dir_current_run_plots_and_animations = run_plan
dir_plots = plots
dir_animations = animations

[geom]
# Особенности геометрии
n_zones = 7 						            # число зон в кейсе, включая объемные, поверхностные и частицы
x_cross_start = -0.46   			            # координата начального поперечного сечения
x_cross_end = 1.69       			            # координата конечного поперечного сечения
discretization_step_show = 0.12		            # шаг дискеретизации при отрисовке поперечных сечений для отображения
discretization_step_export_unsteady = 0.12	    # шаг дискеретизации при отрисовке поперечных сечений для экспорта НЕСТАЦИОНАРНЫХ данных
discretization_step_export_averaged = 0.01	    # шаг дискеретизации при отрисовке поперечных сечений для экспорта ОСРЕДНЁННЫХ данных
frame_width = 9                                 # ширина графического окна
frame_height = 8                                # высота графического окна
view_width = 2.3                                # глубина вида (дальность расположения модели)


x_cross_out = 1.148     			# координата поперечного сечения для замера тяги
slice_position = 0.00   			# координата продольного сечения
n_injectors = 16					# число инжекторов - НУЖНО И ДЛЯ КАРТИНОК РАСПЫЛА, И ДЛЯ ОСРЕДНЕННЫХ ГРАФИКОВ ПОЛНОТЫ!
delta_ts = 0.00004  				# шаг по времени между сохранениями
rotation_angles = 33, 125, -121		# углы поворота модели

[zones]
# Настройка зон. Не задаётся ничего если нет, одиночное значение если одна зона, через запятую если много зон
zone_indices_not_particles = 1, 2, 3, 4, 5, 6       # !!! этот параметр также используется для определения зон для осреднения !!!
zone_indices_particles = 7

[variables]
# Настройка переменных для отображения на рисунках
variables_plot = 'Temperature', 'Pressure', 'Velocity'		# Переменные для отображения на рисунках
variables_legend = 'T (K)', 'P (Па)', 'V (м/с)'				# Подписи легенды		
variables_min = 1200, 0, 0				# Минимальное значение для легенды
variables_max = 3200, 1200000, 1000		# Максимальное значение для легенды
variables_increment = 200, 100000, 100	# Шаг для легенды

species_plot = 'gpg', 'cp', 'air'		# Массовые доли каких компонент отображать
species_ymax = 1, 1, 1					# Максимальные значения массовых долей для легенды
species_increment = 0.1, 0.1, 0.1		# Максимальные значения массовых долей для легенды

particles_variables_plot = 'injection-diameter'
particles_variables_legend = 'd (м)'
particles_variables_min = 0
particles_variables_max = 5e-6
particles_variables_increment = 1e-6

[var_number]
# minimal_mode
x 					= 1
p_stat 				= 4
Y_start 			= 59
t_stat 				= 59		# + n_species
mfr 				= 60		# + n_species
mfr_species 		= 61		# + n_species
# Расчёт ГДФ - вычисление числа Маха и полных T P
v 					= 61		# + n_species * 2
mach 				= 65		# + n_species * 2
t_tot 				= 68		# + n_species * 3
p_tot 				= 69		# + n_species * 3
Ro_Vx_Enthalpy_0 	= 70		# + n_species * 3
Ro_Vx_Vx 			= 71		# + n_species * 3
# Номер переменной при загрузке дат поочередно для определения тяги
Ro_Vx_Vx_Group 		= 59		# + n_species * 4

[average]
average_left = 0					# интервала осреднения - обрезка слева	
average_right = 0					# интервала осреднения - обрезка справа





mfr_fuel_inj = 0.0085																		# расход топлива через один инжектор
folder_equilibrium_state = D:\Simulation\!TECPLOT_MACRO\PYTECPLOT\RESULTS\					# путь к файлу равновесного состава
file_equilibrium_state = Tg-900_Tf-300_Stupa.xlsx											# файл равновесного состава, насчитанный из chemkin
work_path = D:\Simulation\!TECPLOT_MACRO\PYTECPLOT\Result_2019\T900_D71_P\a087\				# СЛЭШ в конце обязательно!!!
# Массовый состав газа на входе. Последний компонент вычисляется как 1-сумма остальных
Species_in = 'O2', 'CO2', 'H2O', 'N2'
Y_in = 0.2317, 0.0004, 0.0505
oxidizer = O2
fuel = C11H21
products = 'CO2', 'H2O'
n_offset = 25                       # в каком сечении измеряется расход - ВАЖНО при определении альфа
n_output = 25                       # в каком сечении измеряются параметры на выходе
n_thrust = 20						# в каком сечении измеряется тяга

# границы расчетной области
x_min = 0.076
x_max = 1.12
x_throat = 1.148					# НЕ ЗНАЮ ЗАЧЕМ НАДО
x_inj = 0.35                 		# Координата расположения инжекторов - при отображении полноты левее этой точки будет 0
# максимальные значения на графиках
t_equil = 2800			# равнове
y_equil = 0.25			# равновесные концентрации (смежная ось)
y_main = 0.3			# массовая доля основных компонент
mfr_fuel = 0.3          # расход топлива
etta = 1.2				# полнота сгорания (смежная ось)
# Имена переменных в таблице равновесного состояния
name_mfr_oxidant = Inlet_flow_rate_of_C1_Inlet2_(kg/sec)
name_mfr_fuel = Inlet_flow_rate_of_C1_Inlet1_(kg/sec)
name_temperature = Temperature_(K)
equilibrium_empty_components = 'CH'								# ЗАГЛУШКА - каких компонент нет в равновесных продуктах при любом альфа
plot_y_main_equil = 'O2', 'CO2', 'CO', 'H2O'
bulk_species = 'N2'
plot_y_main = 'O2', 'CO2', 'H2O', 'CO'
plot_y_minor = 'OH', 'NO', 'O', 'H2'
plot_y_minor_twin = 'N2O', 'CH', 'N'







